### ISSUE TITLE
Missing part of file

### ISSUE THREAD

**Issue by Sept30** [JohnMasoner/unified-focal-loss-pytorch#1]
Hello, some files are missing in the code you provided. Could you please provide them? Thank you

**Comment by JohnMasoner** [comment]
hey @Sept30 ,

I have added this repo to [MONAI](https://github.com/Project-MONAI/MONAI/blob/dev/monai/losses/unified_focal_loss.py), but it does not have MONAI official support, you can clone it down and use it.

by the way, could you tell me which part of the file is really missing?

Mason

**Comment by JohnMasoner** [comment]
> Hello, some files are missing in the code you provided. Could you please provide them? Thank you

hey @Sept30 ,

i'll close the issue, you could open it at any time if you still have questions about the repo.

Mason
